image: gradle:jdk11

services:
  - neo4j:3.5.3

stages:
  - build
  - push
  - deploy
  
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .gradle/  

variables:
  DOCKER_REGISTRY_URL: "registry.netsec.aisec.fraunhofer.de"
  PARENT_PROJECT_NAME: "cpg"

  # for the neo4j service
  NEO4J_AUTH: neo4j/password

  # for the cpg tests to find the neo4j service
  NEO4J_URI: bolt://neo4j

  # we can only cache directories within our project directory
  GRADLE_USER_HOME: ".gradle"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  
build:
  stage: build
  tags:
    - netsec
  before_script:
    # make sure the cached gradle directory exists
    - mkdir -p .gradle  
    - cp netsec.crt /usr/local/share/ca-certificates/netsec.crt
    - update-ca-certificates
    - keytool -import -trustcacerts -cacerts -storepass changeit -file netsec.crt -alias netsec -noprompt-
  script:
    # build
    - echo $GRADLE_PROPERTIES > gradle.properties
    # Note that "sonarqube" already implies "build"
    - gradle --parallel --refresh-dependencies -Dsonar.branch.name=$CI_COMMIT_REF_NAME -Dsonar.host.url=https://sonar.netsec.aisec.fraunhofer.de clean build sonarqube downloadLicenses
  artifacts:
    when: always
    paths:
      - build/reports
