image: gradle:jdk11

services:
  - neo4j:3.5.3

stages:
  - build
  - push
  - deploy

variables:
  DOCKER_REGISTRY_URL: "registry.netsec.aisec.fraunhofer.de"
  PARENT_PROJECT_NAME: "cpg"

  # for the neo4j service
  NEO4J_AUTH: neo4j/password

  # for the cpg tests to find the neo4j service
  NEO4J_URI: bolt://neo4j

build:
  cache: {}
  stage: build
  variables:
    GRADLE_USER_HOME: "/cache/.gradle"
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    PIP_CACHE_DIR: "/cache/.pip"
  tags:
    - netsec
  before_script:
    - cp netsec.crt /usr/local/share/ca-certificates/netsec.crt
    - update-ca-certificates
    - keytool -import -trustcacerts -cacerts -storepass changeit -file netsec.crt -alias netsec -noprompt-
  script:
    # make sure the cached gradle directory exists
    - mkdir -p /cache/.gradle
    # build
    - echo $GRADLE_PROPERTIES > gradle.properties
    - gradle --parallel --refresh-dependencies -Dsonar.host.url=https://sonar.netsec.aisec.fraunhofer.de clean sonarqube
  artifacts:
    when: always
    paths:
      - build/reports
