name: "Run Codecov"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  analyze-code-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11
      - name: Generate report
        run: |
          ./gradlew --parallel --no-daemon check
      - name: Codecov
        uses: codecov/codecov-action@v3.1.1
