name: "Run Codecov"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  analyze-code-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11
      - name: Generate coverage report
        uses: gradle/gradle-build-action@v2
        with:
          arguments: testCodeCoverageReport --continue
      - name: Archive test reports
        uses: actions/upload-artifact@v3
        with:
          name: test
          path: ./code-coverage-report/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./code-coverage-report/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
          fail_ci_if_error: true
          flags: unittests
