name: "Check Dependencies"
on:
  push:
    branches:
      - rh/action-test
      #- main
  #pull_request:
    #branches:
      #- '**'

jobs:
  depcheck:
    runs-on: ubuntu-latest
    name: depcheck
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build project with Gradle
        run: gradle clean build
        
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'Codyze'
          path: '.'
          format: 'SARIF'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 7
            --enableRetired

      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: build/reports/depcheck/depcheck.sarif
