name: "Run Detekt and upload SARIF"

# Run workflow each time code is pushed to the repository.
on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
# does not work yet
#  with-type-resolution:
#    runs-on: ubuntu-latest
#    permissions:
#      # required for all workflows
#      security-events: write
#    steps:
#      - name: Checkout Repo
#        uses: actions/checkout@v3
#
#      - name: Setup Java
#        uses: actions/setup-java@v3
#        with:
#          distribution: "zulu"
#          java-version: 11
#
#      - name: Run detekt
#        run: ./gradlew detektMain detektTest --continue
#
#      # Make sure we always run this upload task,
#      # because the previous step may fail if there are findings.
#      - name: Upload SARIF to Github using the upload-sarif action
#        uses: github/codeql-action/upload-sarif@v2
#        if: success() || failure()
#        with:
#          sarif_file: build/reports/detekt/detekt.sarif

  without-type-resolution:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11

      - name: Run detekt
        run: ./gradlew detekt --continue

      # Make sure we always run this upload task,
      # because the previous step may fail if there are findings.
      - name: Upload SARIF to Github using the upload-sarif action
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/detekt.sarif
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          category: detekt