name: "FindSecBugs"

on:
  push:
    branches:
      - main
      - rh/action-test
  # run on new pushes only for non-draft PRs
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  workflow_dispatch:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build -x check --parallel -Pversion=0.0.0
      # We need to run it multiple times to manually fix the file paths and exclude gradle results
      - name: Run FindSecBugs for Codyze CLI
        uses: advanced-security/spotbugs-findsecbugs-action@v1
        with:
          spotbugs_target: 'codyze-cli/'
          java_distribution: 'temurin'
          java_version: '17'
          path_prefix: 'codyze-cli/src/main/kotlin/'
      - name: Run FindSecBugs for Codyze Core
        uses: advanced-security/spotbugs-findsecbugs-action@v1
        with:
          spotbugs_target: 'codyze-core/'
          java_distribution: 'temurin'
          java_version: '17'
          path_prefix: 'codyze-core/src/main/kotlin/'
      - name: Run FindSecBugs for Codyze CPG Backend
        uses: advanced-security/spotbugs-findsecbugs-action@v1
        with:
          spotbugs_target: 'codyze-backends/cpg/'
          java_distribution: 'temurin'
          java_version: '17'
          path_prefix: 'codyze-backends/cpg/src/main/kotlin/'