# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Gradle Package

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.12
      uses: actions/setup-java@v1
      with:
        java-version: 1.12
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      run: gradle build

    - name: Publish artifact
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      # The GITHUB_REF tag comes in the format 'refs/tags/xxx'.
      # If we split on '/' and take the 3rd value,
      # we can get the release name.
      run: |
        NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
        echo "New version: ${NEW_VERSION}"
        echo "Github username: ${GITHUB_ACTOR}"
        ./gradlew -Pversion=${NEW_VERSION} publish
